FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    openjdk-8-jdk \
    curl \
    unzip \
    wget \
    zip \
    && apt clean

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN curl -sSLO https://github.com/JetBrains/kotlin/releases/download/v1.9.0/kotlin-compiler-1.9.0.zip \
    && unzip kotlin-compiler-1.9.0.zip -d /opt/kotlin \
    && rm kotlin-compiler-1.9.0.zip

ENV PATH="/opt/kotlin/kotlinc/bin:${PATH}"

RUN wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip -O /tmp/gradle.zip \
    && unzip /tmp/gradle.zip -d /opt/gradle \
    && rm /tmp/gradle.zip

ENV GRADLE_HOME=/opt/gradle/gradle-8.7
ENV PATH="${GRADLE_HOME}/bin:${PATH}"

RUN java -version && kotlinc -version && gradle --version

WORKDIR /app

COPY . /app

CMD [ "bash" ]
